"""
Draft intelligence: what strategy you're actually running, what usually
happens at your next pick, and how good the roster you're building is.

These three answer questions a value model structurally cannot. VORP and
VONA price a PLAYER; they say nothing about the SHAPE of the roster you're
assembling or about what the rest of the draft is likely to do to you. The
functions here work on the draft rather than on the board:

  classify_strategy   - names the archetype your picks have committed you to
  pick_intel          - the position odds at your next pick, and crucially
                        what the drafts that FINISHED WELL did there
  roster_percentile   - your roster against a distribution, not a raw total

WHERE THE EVIDENCE COMES FROM, and why that matters: a subscription site
answers these from a corpus of tens of thousands of real drafts it has
collected. There is no such corpus here, so everything below is generated by
simulating this specific draft forward from its current state, many times.

That difference cuts both ways and it's worth being honest about. Their
corpus reflects how humans actually draft, including the irrational bits,
which a simulator will never reproduce. But a simulation conditions on YOUR
exact board, YOUR league settings and the players ALREADY GONE in THIS
draft - where a generic corpus can only match on format and pick number. For
"what should I do at pick 89 given this specific run on tight ends", the
conditioned simulation is the more relevant evidence even though it's
synthetic.
"""
import numpy as np
import pandas as pd
import streamlit as st

from data.draft_board import DRAFTABLE_POSITIONS, snake_pick_numbers, roster_needs
from data.draft_sim import (
    prepare_sim_pool, init_draft_state, run_until_user_pick, record_pick,
    autopick_for_user, optimal_lineup_points, team_on_clock,
)

# Archetypes, defined by what the first several rounds look like. Names match
# the vocabulary drafters already use, so the label carries meaning without
# needing a legend.
#
# Each entry is (label, description, scoring function). A scorer returns a
# raw fit in [0, 1] for a list of (round, position) picks - normalized
# against the other archetypes afterwards, so the absolute scale doesn't
# matter, only the relative ordering.
def _count(picks, pos, through_round=None):
    return sum(1 for r, p in picks if p == pos and (through_round is None or r <= through_round))


def _first_round_of(picks, pos):
    rounds = [r for r, p in picks if p == pos]
    return min(rounds) if rounds else None


def _fit_robust_rb(picks):
    early = _count(picks, 'RB', 3)
    return min(1.0, early / 2.0) if early >= 2 else early * 0.25


def _fit_hero_rb(picks):
    rb_early = _count(picks, 'RB', 2)
    wr_mid = _count(picks, 'WR', 5)
    if rb_early != 1:
        return 0.1 if rb_early == 0 else 0.15
    return min(1.0, 0.45 + 0.18 * wr_mid)


def _fit_zero_rb(picks):
    rb_early = _count(picks, 'RB', 4)
    pass_catchers = _count(picks, 'WR', 4) + _count(picks, 'TE', 4)
    if rb_early > 0:
        return 0.05
    return min(1.0, 0.4 + 0.2 * pass_catchers)


def _fit_zero_wr(picks):
    wr_early = _count(picks, 'WR', 4)
    rb_early = _count(picks, 'RB', 4)
    if wr_early > 0:
        return 0.05
    return min(1.0, 0.4 + 0.2 * rb_early)


def _fit_elite_te(picks):
    first_te = _first_round_of(picks, 'TE')
    if first_te is None:
        return 0.02
    if first_te <= 3:
        return 1.0
    if first_te <= 5:
        return 0.45
    return 0.1


def _fit_late_qb(picks):
    first_qb = _first_round_of(picks, 'QB')
    qb_count = _count(picks, 'QB')
    if first_qb is None:
        return 0.35          # still consistent with waiting, just unproven
    if first_qb >= 8:
        return 1.0 if qb_count >= 2 else 0.8
    if first_qb >= 6:
        return 0.5
    return 0.05


def _fit_early_qb(picks):
    first_qb = _first_round_of(picks, 'QB')
    if first_qb is None:
        return 0.05
    return 1.0 if first_qb <= 3 else (0.4 if first_qb <= 5 else 0.05)


def _fit_balanced(picks):
    if not picks:
        return 0.5
    through = [p for r, p in picks if r <= 6]
    if not through:
        return 0.5
    counts = pd.Series(through).value_counts(normalize=True)
    # Even spread across positions = balanced. Measured as how far the
    # distribution sits from a single-position concentration.
    return float(1.0 - counts.max())


STRATEGIES = [
    ('HeroRB', 'One anchor back, then receivers', _fit_hero_rb),
    ('RobustRB', 'Two-plus backs in the first three rounds', _fit_robust_rb),
    ('ZeroRB', 'No backs early, load pass catchers', _fit_zero_rb),
    ('ZeroWR', 'Backs early, receivers later', _fit_zero_wr),
    ('EliteTE', 'Premium tight end taken early', _fit_elite_te),
    ('LateQB', 'Wait on quarterback', _fit_late_qb),
    ('EarlyQB', 'Quarterback inside the first three rounds', _fit_early_qb),
    ('Balanced', 'No strong positional lean', _fit_balanced),
]

# Confidence ceiling. A strategy read from a handful of picks is a
# description, not a prediction - the draft can still break it in either
# direction - so this never claims certainty no matter how clean the
# pattern looks.
MAX_STRATEGY_CONFIDENCE = 0.85
CONFIDENCE_FULL_EVIDENCE_PICKS = 7


def classify_strategy(my_roster, settings=None):
    """
    Name the archetype your picks have committed you to, with rivals and a
    confidence.

    Deliberately descriptive rather than prescriptive: it reads what you have
    ALREADY done rather than telling you what to do. That's the useful
    framing mid-draft - "you're two picks into Zero RB, here's what that
    usually needs next" beats an abstract recommendation, and it makes the
    downstream pick odds interpretable.

    Confidence rises with picks made and with how far the leader is clear of
    the runner-up, and is capped (see MAX_STRATEGY_CONFIDENCE). With no picks
    at all it is exactly zero and the label means nothing yet.
    """
    picks = [(int(p.get('round') or i + 1), str(p.get('Pos', '')).upper())
             for i, p in enumerate(my_roster or [])]
    picks = [(r, p) for r, p in picks if p in DRAFTABLE_POSITIONS]

    scored = [(key, label, max(0.0, float(fn(picks)))) for key, label, fn in STRATEGIES]
    total = sum(s for _, _, s in scored)
    if total <= 0:
        return {'primary': None, 'label': 'Not classified yet', 'confidence': 0.0, 'candidates': []}

    scored.sort(key=lambda t: -t[2])
    candidates = [{'id': key, 'label': label, 'weight': round(score / total, 3)}
                  for key, label, score in scored[:3]]

    if not picks:
        return {'primary': None, 'label': 'Not classified yet', 'confidence': 0.0,
                'candidates': candidates}

    evidence = min(1.0, len(picks) / CONFIDENCE_FULL_EVIDENCE_PICKS)
    separation = candidates[0]['weight'] - (candidates[1]['weight'] if len(candidates) > 1 else 0.0)
    confidence = round(min(MAX_STRATEGY_CONFIDENCE, evidence * (0.45 + 1.4 * separation)), 2)
    return {'primary': candidates[0]['id'], 'label': candidates[0]['label'],
            'confidence': confidence, 'candidates': candidates}


def init_state_from_live(board, settings, my_roster, all_drafted, rounds, my_slot):
    """
    Seed a simulation from a draft already in progress.

    Everyone already taken is removed from the pool; your own picks go onto
    your roster, and everyone else's are spread across the other teams. The
    spread is approximate - in a live draft you generally know WHO went, not
    which manager took them - but it only feeds the bots' roster-legality
    rules, and being roughly right about how many backs the room already
    holds is enough for that. Your own roster, which is what every
    recommendation keys off, is exact.
    """
    state = init_draft_state(settings, my_slot, rounds)
    n_teams = int(settings['num_teams'])
    mine = {p['Player'] for p in (my_roster or [])}

    other_team = 1
    for pick in (all_drafted or []):
        name = pick.get('Player')
        row = board[board['Player'] == name]
        if row.empty:
            continue
        if name in mine:
            team = my_slot
        else:
            if other_team == my_slot:
                other_team = other_team % n_teams + 1
            team = other_team
            other_team = other_team % n_teams + 1
        record_pick(state, team, row.iloc[0])
    return state


@st.cache_data(show_spinner=False, ttl=600)
def pick_intel(_board, _settings, my_slot, rounds, drafted_signature, n_sims=40,
               reach_window=3.0, look_ahead=3):
    """
    Simulate this draft forward many times and report, for each of your
    upcoming picks, which positions you ended up taking - overall, and
    restricted to the runs that finished in the top quartile.

    The top-quartile split is the part worth having. "RB goes here 45% of the
    time" is a description of the field; "in the drafts that finished best
    from this exact spot, you took RB here 71% of the time" is advice. It is
    the same distinction between average and good play that makes a corpus
    of real drafts useful, recovered here by conditioning on outcome instead
    of on other people.

    Cached on a signature of who's already been drafted rather than on the
    board frame, so it recomputes when the draft moves and not when an
    unrelated widget does. Underscore-prefixed frames are excluded from the
    hash for the reason documented in data.transforms.
    """
    pool, order_col, has_adp = prepare_sim_pool(_board, _settings.get('bot_weights'))
    if pool.empty:
        return {}

    drafted = list(drafted_signature or [])
    drafted_rows = [{'Player': name, 'mine': mine} for name, mine in drafted]
    my_roster_seed = [r for r in drafted_rows if r['mine']]

    runs = []
    for sim in range(int(n_sims)):
        state = init_state_from_live(_board, _settings, my_roster_seed, drafted_rows,
                                     rounds, my_slot)
        state['seed'] = 90001 + sim * 7919
        picks_before = len(state['rosters'][my_slot])
        rng = np.random.default_rng(state['seed'])
        while not state['complete']:
            run_until_user_pick(state, _settings, pool, order_col, reach_window=reach_window)
            if state['complete']:
                break
            choice = autopick_for_user(state, _settings, pool, explore=0.6, rng=rng)
            if choice is None:
                break
            record_pick(state, my_slot, choice)
        mine_final = state['rosters'][my_slot]
        score, _ = optimal_lineup_points(mine_final, _settings)
        new_picks = mine_final[picks_before:]
        # Indexed by which of YOUR picks it is, not by the simulator's round
        # number. The tracker only knows about picks you've actually marked,
        # so a live draft where you've logged your own four picks but not the
        # other forty leaves the simulator's round counter far behind the
        # real draft - and labelling this "round 1" while you're sitting in
        # round 5 is worse than not labelling it. Your own pick sequence is
        # always correct regardless of how completely the room is tracked.
        runs.append({'score': score,
                     'picks': [(picks_before + i + 1, p['Pos'])
                               for i, p in enumerate(new_picks)]})

    if not runs:
        return {}

    scores = np.array([r['score'] for r in runs], dtype=float)
    cutoff = np.quantile(scores, 0.75)
    top_runs = [r for r in runs if r['score'] >= cutoff]

    def _freq(subset, round_no):
        positions = [pos for run in subset for rnd, pos in run['picks'] if rnd == round_no]
        if not positions:
            return []
        counts = pd.Series(positions).value_counts()
        total = int(counts.sum())
        return [{'pos': pos, 'count': int(c), 'freq': round(c / total, 3)}
                for pos, c in counts.items()]

    upcoming = sorted({idx for run in runs for idx, _ in run['picks']})[:look_ahead]
    return {
        'sims': len(runs),
        'has_adp': has_adp,
        'score_distribution': scores.tolist(),
        'top_quartile_cutoff': round(float(cutoff), 1),
        'rounds': [{
            'pick_index': idx,
            'sample': sum(1 for run in runs for i2, _ in run['picks'] if i2 == idx),
            'positions': _freq(runs, idx),
            'top_quartile': _freq(top_runs, idx),
        } for idx in upcoming],
    }


@st.cache_data(show_spinner=False, ttl=900)
def outcome_distribution(_board, _settings, my_slot, rounds, n_sims=40, reach_window=3.0):
    """
    The spread of starting-lineup scores achievable from a draft slot, used
    to grade a roster as a percentile rather than a bare point total.

    A total on its own is unreadable - 1,850 points means nothing without
    knowing that this slot in this format produces 1,700 to 1,950. The
    percentile is the number people can actually act on, and it's exactly
    what the reference sites report.
    """
    from data.draft_sim import run_many_drafts
    _, outcomes = run_many_drafts(_board, _settings, my_slot, rounds,
                                  n_sims=int(n_sims), reach_window=reach_window)
    if outcomes is None or outcomes.empty:
        return {}
    scores = outcomes['Starters Proj'].to_numpy(dtype=float)
    return {'scores': scores.tolist(), 'n': int(len(scores)),
            'median': float(np.median(scores)),
            'p25': float(np.quantile(scores, 0.25)),
            'p75': float(np.quantile(scores, 0.75))}


def roster_percentile(score, distribution):
    """Where a starting-lineup score falls in the simulated distribution."""
    if not distribution or not distribution.get('scores'):
        return None
    scores = np.asarray(distribution['scores'], dtype=float)
    if len(scores) == 0:
        return None
    return round(float((scores < float(score)).mean() * 100), 0)


def _projected_full_lineup(available, my_roster, settings):
    """
    What your starting lineup would score if every empty slot were filled at
    replacement level - the sensible denominator for "how much does this
    pick add to my team".
    """
    from data.draft_sim import optimal_lineup_points
    from data.draft_board import DRAFTABLE_POSITIONS as _POS

    filled, _ = optimal_lineup_points(my_roster, settings)
    needs = roster_needs(my_roster, settings)
    replacement_total = 0.0
    for slot, count in needs.items():
        if count <= 0:
            continue
        positions = {'FLEX': ['RB', 'WR', 'TE'],
                     'SUPERFLEX': ['QB', 'RB', 'WR', 'TE']}.get(slot, [slot])
        pool = available[available['Pos'].astype(str).str.upper().isin(positions)]
        pool = pool.dropna(subset=['Proj Pts']).sort_values('Proj Pts', ascending=False)
        if pool.empty:
            continue
        # "Replacement" here is the player around the depth this league
        # rosters at that slot, not the best one left.
        depth = min(len(pool) - 1, int(settings['num_teams']) * max(1, count))
        replacement_total += float(pool['Proj Pts'].iloc[depth]) * count
    return max(float(filled) + replacement_total, 1.0)


def _replacement_context(available, settings):
    """
    The three things contingency value needs: how many lineup slots each
    position occupies on one roster, how often a player at it is absent, and
    what a waiver pickup at it is worth.
    """
    from data.draft_board import (
        lineup_slots_per_team, measure_absence_rates, compute_starter_demand,
        DRAFTABLE_POSITIONS as _POSITIONS,
    )
    slots = lineup_slots_per_team(available, settings)
    absence = measure_absence_rates(settings.get('baseline_season', 2025))
    started = compute_starter_demand(available, settings)

    # What you'd get off waivers at each position: the best player past the
    # point where the league's rosters run out. Measured off this board so it
    # moves with scoring settings rather than being a constant.
    waiver = {}
    for pos in _POSITIONS:
        pts = (available.loc[available['Pos'].astype(str).str.upper() == pos, 'Proj Pts']
               .dropna().sort_values(ascending=False).to_numpy())
        if not len(pts):
            continue
        idx = min(int(started.get(pos, 0)), len(pts) - 1)
        waiver[pos] = float(pts[idx])
    return {'slots': slots, 'absence': absence, 'waiver': waiver}


def _contingency_value(player, pos, my_roster, settings, replacement):
    """
    What a player who does NOT crack your starting lineup is worth: an
    OPTION on him beating what you could have picked up free, in the weeks
    he'd actually be startable.

    Two things make this the right shape for a late pick, and both are
    missing from a plain points-above-replacement read:

    An option is valued on its upside, not its mean. You are not stuck with
    a late-round pick who busts - you drop him and stream the position, so
    the downside is bounded at roughly zero while the upside is a starter
    you didn't pay for. That is why late running backs are worth more than
    their projections suggest (one injury ahead of them and they inherit a
    workload) and why a safe, low-variance backup is worth less than it
    looks. Computed as E[max(X - waiver, 0)] with X normal around the
    projection, its spread taken from the board's own Ceiling.

    And the option only pays in weeks he'd be in your lineup, which is
    where expected_start_share comes in - the whole answer to "should I
    take another tight end". A third receiver walks into a flex slot nearly
    every week; a second tight end plays about three weeks a year and a
    third plays none, because only one can ever start. Pricing both off
    league-wide surplus says they're comparable. They are not.
    """
    from data.draft_board import depth_multiplier

    points = player.get('Proj Pts')
    if points is None or pd.isna(points):
        return 0.0
    share = depth_multiplier(pos, my_roster, replacement['slots'], replacement['absence'])
    if share <= 0:
        return 0.0

    mean = float(points)
    waiver = float(replacement['waiver'].get(pos, 0.0))
    ceiling = player.get('Ceiling')
    # Ceiling is the 85th percentile outcome, which is 1.036 standard
    # deviations up. Falling back to a quarter of the projection keeps this
    # working on a board with no outcome range attached.
    if ceiling is not None and pd.notna(ceiling) and float(ceiling) > mean:
        sigma = max(1.0, (float(ceiling) - mean) / 1.036)
    else:
        sigma = max(1.0, 0.25 * abs(mean))

    z = (waiver - mean) / sigma
    density = float(np.exp(-0.5 * z * z) / np.sqrt(2 * np.pi))
    from data.draft_sources import normal_sf
    expected_excess = sigma * density + (mean - waiver) * normal_sf(z)
    return max(0.0, share * expected_excess)


def positional_value_add(board, my_roster, settings, next_pick, drafted_names=None,
                         picks_left=None):
    """
    What spending THIS pick on each position does to your projected starting
    lineup, in points and as a percentage.

    The question every drafter is actually asking on the clock is not "who is
    the best player left" but "which hole should I fill now, and which can
    wait". This answers it directly: for each position, the value of taking
    the best one available RIGHT NOW, minus the value of the one you'd
    expect to still be there at your NEXT pick. What's left is the cost of
    waiting - which is the whole decision.

    Why it's a difference and not a level: the best receiver available is
    always worth a lot of points in absolute terms, so ranking positions by
    "how good is the best one" just re-sorts them by raw scoring and tells
    you to take a quarterback every time. Subtracting what you'd get by
    waiting removes exactly that, and leaves the scarcity - a tight end who
    won't be there next round scores high, a quarterback with eight
    comparable ones behind him scores near zero.

    Marginal gain is measured against your ACTUAL lineup, so a position you
    have already filled contributes only bench value and correctly falls to
    the bottom. Both terms use the same lineup calculation, so the
    difference is apples to apples.

    (Fantasy Football Advice show a comparable per-position score built from
    how often similar drafts took each position here, plus server-side
    "dynamic position multipliers" whose derivation isn't in their client
    bundle. This is a different route to the same question - and it has the
    advantage of being computable from your own board and fully explainable
    line by line.)

    Returns rows sorted by value added, each carrying the player driving it.
    """
    from data.draft_sim import marginal_lineup_gain, optimal_lineup_points

    if board is None or board.empty:
        return []
    available = board
    if drafted_names:
        available = available[~available['Player'].isin(set(drafted_names))]
    if available.empty or 'Proj Pts' not in available.columns:
        return []

    replacement = _replacement_context(available, settings)

    # "The cost of waiting" presumes you can wait, and in the last rounds you
    # can't - every remaining pick is a roster spot you will never get back.
    # With one pick left there is no next turn at all, so the whole value of
    # spending it here is the LEVEL, not the drop-off. This discounts the
    # wait-one-turn term by how likely you are to still have a spot for the
    # position later, which is what makes the panel keep saying something
    # useful late instead of collapsing to six zeros.
    #
    # At ten picks left it's 0.9 and early-round behaviour is unchanged,
    # which matters because the drop-off read is the right one there and the
    # user should not see it move.
    if picks_left is None:
        wait_weight = 1.0
    else:
        remaining = max(1, int(picks_left))
        wait_weight = float(np.clip((remaining - 1) / remaining, 0.0, 1.0))

    # Percentages are against a COMPLETE projected lineup, not the partial
    # one you happen to hold right now. Dividing by the current roster makes
    # the first pick of a draft read "+10,060% to your team", which is not
    # only absurd but hides the ordering the number exists to show. Empty
    # starting slots are valued at replacement level, which is what you'd
    # end up with if you never addressed them.
    baseline = _projected_full_lineup(available, my_roster or [], settings)

    rows = []
    for pos in DRAFTABLE_POSITIONS:
        pool = available[available['Pos'].astype(str).str.upper() == pos]
        pool = pool.dropna(subset=['Proj Pts']).sort_values('Proj Pts', ascending=False)
        if pool.empty:
            continue

        best = pool.iloc[0]
        # Once every starting slot is full, marginal_lineup_gain is exactly
        # zero for every position - the lineup can't improve, so all six
        # cards read 0% and the panel stops saying anything for the whole
        # back half of the draft. That's a real modelling gap, not just a
        # display one: a bench receiver and a third tight end are worth
        # visibly different amounts, because one of them will be in your
        # lineup some weeks and the other never will.
        #
        # max() of the two, because they're the same quantity measured two
        # ways - points this player adds to your season, as a starter or as
        # depth - and whichever is larger is the role he'd actually fill.
        gain_now = max(
            marginal_lineup_gain(
                my_roster or [],
                {'Pos': pos, 'Proj Pts': best['Proj Pts'], 'VORP': best.get('VORP')},
                settings),
            _contingency_value(best, pos, my_roster, settings, replacement))

        # Expected best still on the board at your next pick: walk the
        # position in value order, weighting each player by the chance he is
        # both available AND the best one left.
        expected_points = float(best['Proj Pts'])
        if next_pick is not None and 'Avail Next %' in pool.columns:
            survive = (pd.to_numeric(pool['Avail Next %'], errors='coerce').fillna(0) / 100.0).to_numpy()
            points = pool['Proj Pts'].to_numpy(dtype=float)
            gone_before = np.cumprod(np.concatenate([[1.0], 1.0 - survive[:-1]]))
            weights = survive * gone_before
            total_weight = float(weights.sum())
            if total_weight > 0.02:
                expected_points = float((weights * points).sum() / total_weight)
            else:
                # Nobody at this position is expected to survive: waiting
                # gets you replacement level, not the next name down.
                expected_points = float(points[-1])

        # Same treatment for the wait-one-turn side, so the subtraction below
        # stays a difference of two like quantities rather than a starter
        # value minus a depth value.
        expected_ceiling = None
        if 'Ceiling' in pool.columns and pd.notna(best.get('Ceiling')) and best['Proj Pts']:
            # Scale the best player's ceiling-to-projection ratio onto the
            # weaker player you'd expect to be left.
            ratio = float(best['Ceiling']) / float(best['Proj Pts'])
            expected_ceiling = expected_points * ratio
        gain_later = max(
            marginal_lineup_gain(
                my_roster or [], {'Pos': pos, 'Proj Pts': expected_points, 'VORP': None},
                settings),
            _contingency_value({'Proj Pts': expected_points, 'Ceiling': expected_ceiling},
                               pos, my_roster, settings, replacement))

        value_add = gain_now - wait_weight * gain_later
        rows.append({
            'Pos': pos,
            'Best available': best['Player'],
            'Proj Pts': round(float(best['Proj Pts']), 1),
            'If you wait': round(expected_points, 1),
            'Points added': round(value_add, 1),
            'Team %': round(value_add / baseline * 100, 1),
            'Avail Next %': best.get('Avail Next %'),
        })

    return sorted(rows, key=lambda r: -r['Points added'])


def positional_run_pressure(all_drafted, settings, lookback=12):
    """
    Which positions the room is taking faster than it "should" right now.

    A run is the thing that actually costs you players between picks, and it
    is invisible on a board sorted by value - by the time you notice the
    tight ends are gone, they're gone. Comparing the last dozen picks
    against the league's overall positional demand turns that into a number
    you can see coming.

    Positive pressure = going faster than baseline demand.
    """
    picks = [str(p.get('Pos', '')).upper() for p in (all_drafted or [])]
    if len(picks) < 4:
        return []
    recent = picks[-int(lookback):]
    recent_share = pd.Series(recent).value_counts(normalize=True)

    roster = settings['roster']
    demand = {}
    for pos in DRAFTABLE_POSITIONS:
        slots = int(roster.get(pos, 0))
        if pos in ('RB', 'WR', 'TE'):
            slots += int(roster.get('FLEX', 0)) / 3.0
        if pos in ('QB', 'RB', 'WR', 'TE'):
            slots += int(roster.get('SUPERFLEX', 0)) / 4.0
        demand[pos] = slots
    total_demand = sum(demand.values()) or 1.0

    rows = []
    for pos in DRAFTABLE_POSITIONS:
        baseline = demand[pos] / total_demand
        actual = float(recent_share.get(pos, 0.0))
        rows.append({'Pos': pos,
                     'Recent share': round(actual * 100, 0),
                     'Baseline share': round(baseline * 100, 0),
                     'Pressure': round((actual - baseline) * 100, 0)})
    return sorted(rows, key=lambda r: -r['Pressure'])
